{{- include "signari.validate" . -}}
{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "signari.fullname" . }}-secrets
  labels:
    {{- include "signari.labels" . | nindent 4 }}
type: Opaque
stringData:
  SIGNARI_DSN: {{ .Values.secret.dsn | quote }}
  SIGNARI_ROOT_KEY: {{ .Values.secret.rootKey | quote }}
  SIGNARI_ROOT_KEY_REF: {{ .Values.secret.rootKeyRef | quote }}
  {{- if .Values.secret.adminToken }}
  SIGNARI_ADMIN_TOKEN: {{ .Values.secret.adminToken | quote }}
  {{- end }}
{{- end }}
