package posture

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// Chrome Enterprise device trust, as a source of device posture.
//
// # What it is
//
// A managed Chrome installation can prove which device it is running on. The
// browser signs a challenge with a key held by the device and attested by
// Google, and Google's Verified Access API turns the signed response back into
// facts: which device, whether it is managed by this customer, whether disk
// encryption and screen lock are on.
//
// # Why it is a posture source rather than a feature
//
// Signari already has a device posture layer with two sources — a client
// certificate, and a header from a trusted proxy — and an access policy that
// speaks `device_managed` and `device_compliant`. Chrome device trust is a
// third source of the same facts.
//
// Making it a source rather than a parallel concept means every policy already
// written keeps working, `signari policy test` covers it, and there is one
// answer to "was this device trusted" rather than two that can disagree.
//
// # Evidence, not assertion
//
// The verdict comes from Google's response to a signed challenge, not from a
// header the browser sent. A header saying "this device is managed" is worth
// exactly as much as the network path it crossed; this is a signature over a
// nonce the server issued.

// VerifiedAccessEndpoint is Google's challenge verification API.
const VerifiedAccessEndpoint = "https://verifiedaccess.googleapis.com/v2"

// Chrome verifies device trust responses.
type Chrome struct {
	// Token is a bearer token for the Verified Access API, from a service
	// account with the Verified Access scope.
	Token func(ctx context.Context) (string, error)
	// CustomerID is the Google Workspace customer this deployment belongs to.
	//
	// Checked against what Google reports. Without it a signed response from a
	// device managed by ANY Workspace customer would be accepted, which turns
	// "a managed device" into "someone's managed device".
	CustomerID string

	HTTP    *http.Client
	BaseURL string // overridden in tests
}

func (c *Chrome) base() string {
	if c.BaseURL != "" {
		return strings.TrimRight(c.BaseURL, "/")
	}
	return VerifiedAccessEndpoint
}

func (c *Chrome) client() *http.Client {
	if c.HTTP != nil {
		return c.HTTP
	}
	return &http.Client{Timeout: 10 * time.Second}
}

// Challenge asks Google for a challenge to hand the browser.
//
// The challenge is generated by Google rather than by us, which is what makes
// the response verifiable: Google checks the signature against the device key
// it attested, and it will only do that for a challenge it issued.
func (c *Chrome) Challenge(ctx context.Context) (string, error) {
	var out struct {
		Challenge string `json:"challenge"`
	}
	if err := c.call(ctx, "/challenge:generate", map[string]any{}, &out); err != nil {
		return "", err
	}
	if out.Challenge == "" {
		return "", fmt.Errorf("google returned an empty challenge")
	}
	return out.Challenge, nil
}

// verifyResponse is what Google returns for a signed challenge.
type verifyResponse struct {
	DeviceSignal struct {
		DeviceEnrollmentDomain string `json:"deviceEnrollmentDomain"`
		DiskEncrypted          string `json:"diskEncrypted"`
		ScreenLockSecured      string `json:"screenLockSecured"`
		OSFirewall             string `json:"osFirewall"`
	} `json:"deviceSignal"`
	DevicePermanentID string `json:"devicePermanentId"`
	SignedPublicKey   string `json:"signedPublicKeyAndChallenge"`
	CustomerID        string `json:"customerId"`
	// KeyTrustLevel says whether the key is attested by hardware. A software
	// key proves the browser profile, not the device.
	KeyTrustLevel string `json:"keyTrustLevel"`
}

// Verify turns a signed challenge response into device posture.
func (c *Chrome) Verify(ctx context.Context, challengeResponse string) (State, error) {
	if challengeResponse == "" {
		return State{Source: "none"}, nil
	}
	var out verifyResponse
	if err := c.call(ctx, "/challenge:verify", map[string]any{
		"challengeResponse": challengeResponse,
	}, &out); err != nil {
		return State{Source: "none"}, err
	}

	// A response Google verified but which belongs to a different Workspace
	// customer is not our device. Without this check "managed" means "managed by
	// somebody", which is not a security property.
	if c.CustomerID != "" && out.CustomerID != "" &&
		!strings.EqualFold(out.CustomerID, c.CustomerID) {
		return State{Source: "chrome:foreign-customer"},
			fmt.Errorf("the device is managed by another Google Workspace customer")
	}

	// A key that is not hardware-attested proves a browser profile rather than a
	// device. Reported as unmanaged rather than refused: it is still a signal,
	// and a policy that demands managed devices will refuse it anyway.
	//
	// The values are Google's enum, not prose: CHROME_BROWSER_HW_KEY is the
	// hardware one and CHROME_BROWSER_OS_KEY is not. Matching on the word
	// "HARDWARE" reads correctly and never fires, which is how every device ends
	// up reported as a software key.
	if out.KeyTrustLevel != "" && !hardwareKey(out.KeyTrustLevel) {
		return State{Managed: false, Compliant: false, Source: "chrome:software-key"}, nil
	}

	managed := out.DeviceSignal.DeviceEnrollmentDomain != ""
	// Compliant means the posture signals Google reports are all satisfied.
	// Absent signals are NOT treated as satisfied: a policy that has not been
	// pushed to a device reports nothing, and reading that as compliance is how
	// an unencrypted laptop passes a disk-encryption requirement.
	compliant := managed &&
		isTrue(out.DeviceSignal.DiskEncrypted) &&
		isTrue(out.DeviceSignal.ScreenLockSecured)

	return State{Managed: managed, Compliant: compliant, Source: "chrome"}, nil
}

// hardwareKey reports whether the attestation key lives in hardware.
//
// CHROME_BROWSER_HW_KEY only. CHROME_BROWSER_OS_KEY is held by the operating
// system and proves the browser profile; KEY_TRUST_LEVEL_UNSPECIFIED proves
// nothing at all.
func hardwareKey(level string) bool {
	return strings.EqualFold(level, "CHROME_BROWSER_HW_KEY")
}

// isTrue reads Google's tri-state posture signals.
//
// They are strings: "ENCRYPTED", "UNSUPPORTED", "UNKNOWN". Only the positive
// value counts — "UNKNOWN" means the device did not say, and treating silence
// as compliance defeats the check.
func isTrue(v string) bool {
	switch strings.ToUpper(v) {
	case "ENCRYPTED", "ENABLED", "SECURED", "TRUE":
		return true
	}
	return false
}

func (c *Chrome) call(ctx context.Context, path string, body, out any) error {
	if c.Token == nil {
		return fmt.Errorf("chrome device trust is not configured")
	}
	tok, err := c.Token(ctx)
	if err != nil {
		return err
	}
	raw, err := json.Marshal(body)
	if err != nil {
		return err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.base()+path,
		bytes.NewReader(raw))
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", "Bearer "+tok)
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.client().Do(req)
	if err != nil {
		return fmt.Errorf("verified access API: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode >= 400 {
		msg, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		return fmt.Errorf("verified access API %s: %s", resp.Status,
			strings.TrimSpace(string(msg)))
	}
	return json.NewDecoder(io.LimitReader(resp.Body, 1<<20)).Decode(out)
}
