package passwords

import (
	"context"
	"crypto/sha256"
	"encoding/base64"
	"testing"

	"golang.org/x/crypto/pbkdf2"
)

// Cross-implementation vectors. Every hash here was produced by ANOTHER program
// -- PHP's crypt(3) and an independent PHP phpass implementation -- not by this
// package. A verifier that only agrees with itself is worthless for migration:
// it would accept nothing a real system ever wrote, and the failure would look
// like every imported user typing the wrong password.
func TestForeignHashVectors(t *testing.T) {
	const pw = "correct-horse"

	for _, tc := range []struct {
		name, hash string
	}{
		// WordPress / phpBB, generated by an independent PHP implementation.
		{"phpass",
			"$P$Babcdefghz3ByWd5584TNs0JQphRgs1"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			h := NewHasher(MemoryBudgetMiB)
			needsRehash, err := h.Verify(context.Background(), tc.hash, pw)
			if err != nil {
				t.Fatalf("a real %s hash was rejected: %v", tc.name, err)
			}
			// Every foreign format is by definition not current policy, so a
			// successful sign-in must upgrade it to Argon2id.
			if !needsRehash {
				t.Error("a foreign hash did not request a rehash; it would stay foreign forever")
			}

			// And the wrong password must still fail.
			if _, err := h.Verify(context.Background(), tc.hash, pw+"x"); err == nil {
				t.Fatal("the wrong password was ACCEPTED")
			}
		})
	}
}

// Failing open on a malformed or unknown hash turns a bad import into an
// authentication bypass for every affected user at once.
// SHA-crypt is not supported yet (see passwords.go). It must be REFUSED, not
// silently accepted -- and this test is what will fail, usefully, on the day
// somebody wires in an implementation that does not agree with glibc.
func TestUnsupportedSHACryptIsRefused(t *testing.T) {
	h := NewHasher(MemoryBudgetMiB)
	real := "$6$rounds=5000$abcdefghijklmnop$nmNyAaH/6gBRHJoLPwH1/AtpW5kLUN.F9idLxlyXJao/QMkkQWfPO87.ci./j.XYEWTw7OiynLl88jj3T2bDX1"
	if _, err := h.Verify(context.Background(), real, "correct-horse"); err == nil {
		t.Fatal("SHA-crypt reported as verified while unsupported")
	}
}

func TestMalformedForeignHashesNeverPass(t *testing.T) {
	h := NewHasher(MemoryBudgetMiB)
	for _, bad := range []string{
		"", "$", "$6$", "$6$salt", "$5$$", "$P$", "$P$B", "$P$Bshort",
		"$scrypt$", "$scrypt$ln=99,r=8,p=1$AA$AA", // absurd cost must be refused, not attempted
		"$9$unknown$hash", "plaintext", "$2b$notreallybcrypt",
	} {
		if _, err := h.Verify(context.Background(), bad, "anything"); err == nil {
			t.Errorf("malformed hash %q was ACCEPTED", bad)
		}
	}
}

// Keycloak keeps its parameters in a JSON blob beside the hash rather than in
// the hash string, so it needs its own entry point.
func TestKeycloakCredential(t *testing.T) {
	// Built with the same PBKDF2 the exporter uses, so this checks the parsing
	// and the parameter handling rather than the primitive.
	const credentialData = `{"hashIterations":27500,"algorithm":"pbkdf2-sha256"}`

	// Wrong shapes must be refused rather than panicking or passing.
	for _, tc := range []struct{ cd, sd string }{
		{"not json", `{"value":"AA","salt":"AA"}`},
		{credentialData, "not json"},
		{`{"hashIterations":0,"algorithm":"pbkdf2-sha256"}`, `{"value":"AA","salt":"AA"}`},
		{`{"hashIterations":27500,"algorithm":"md5"}`, `{"value":"AA","salt":"AA"}`},
		// An absurd iteration count would let a corrupt import stall the login path.
		{`{"hashIterations":999999999,"algorithm":"pbkdf2-sha256"}`, `{"value":"AA","salt":"AA"}`},
	} {
		if err := VerifyKeycloak(tc.cd, tc.sd, "pw"); err == nil {
			t.Errorf("accepted malformed keycloak credential: %s / %s", tc.cd, tc.sd)
		}
	}
}

// A Keycloak credential must survive the pack/verify round trip through the
// normal dispatch, so an imported user signs in on the same path as everyone
// else and gets upgraded to Argon2id on first success.
func TestKeycloakPackedRoundTrip(t *testing.T) {
	// Built with the same PBKDF2-SHA256 Keycloak uses, so this exercises the
	// packing and dispatch rather than re-testing the primitive.
	const salt = "c2FsdHNhbHRzYWx0c2FsdA" // 16 bytes, base64
	cd := `{"hashIterations":1000,"algorithm":"pbkdf2-sha256"}`
	sd := keycloakSecretData(t, "correct-horse", salt, 1000)

	stored := EncodeKeycloak(cd, sd)
	h := NewHasher(MemoryBudgetMiB)

	needsRehash, err := h.Verify(context.Background(), stored, "correct-horse")
	if err != nil {
		t.Fatalf("a packed Keycloak credential was rejected: %v", err)
	}
	if !needsRehash {
		t.Error("an imported Keycloak hash did not request a rehash")
	}
	if _, err := h.Verify(context.Background(), stored, "wrong"); err == nil {
		t.Fatal("the wrong password was accepted")
	}
}

// keycloakSecretData builds the secretData blob Keycloak stores.
func keycloakSecretData(t *testing.T, password, saltB64 string, iterations int) string {
	t.Helper()
	salt, err := base64.StdEncoding.DecodeString(saltB64 + "==")
	if err != nil {
		t.Fatal(err)
	}
	key := pbkdf2.Key([]byte(password), salt, iterations, 32, sha256.New)
	return `{"value":"` + base64.StdEncoding.EncodeToString(key) +
		`","salt":"` + base64.StdEncoding.EncodeToString(salt) + `"}`
}
